# Generated by Django 5.0.1 on 2024-02-21 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('groupnamec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.groupmodel')),
            ],
        ),
    ]
